# Generated by Django 5.0.4 on 2024-05-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
