# Generated by Django 5.0.4 on 2024-05-13 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_company_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('job_requirement', models.CharField(max_length=1000)),
                ('job_type', models.CharField(max_length=100)),
                ('job_package', models.CharField(max_length=100)),
                ('last_date', models.DateTimeField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
        ),
    ]
