# Generated by Django 5.0.4 on 2024-05-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_jobposting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='establishment_year',
            field=models.CharField(max_length=4),
        ),
    ]
