# Generated by Django 5.0.4 on 2024-05-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_student_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='company_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
