# Generated by Django 5.0.4 on 2024-05-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_appliedcandidates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedcandidates',
            old_name='job_posting',
            new_name='job_id',
        ),
        migrations.RemoveField(
            model_name='appliedcandidates',
            name='student',
        ),
        migrations.AddField(
            model_name='appliedcandidates',
            name='student_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
