# Generated by Django 5.0.4 on 2024-05-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_jobposting_status_alter_jobposting_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedcandidates',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
