# Generated by Django 5.0.4 on 2024-05-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='student',
        ),
        migrations.AddField(
            model_name='notification',
            name='student_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
