# Generated by Django 5.0.4 on 2024-05-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_notification_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcandidates',
            name='student_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
